# Generated by Django 4.1 on 2022-08-10 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_remove_product_tag_delete_order_delete_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('female', 'female'), ('male', 'male')], max_length=200, null=True),
        ),
    ]
