# Generated by Django 4.1 on 2022-08-10 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_customer_gender_type_alter_customer_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='gender',
        ),
    ]
