# Generated by Django 4.1 on 2022-08-10 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_remove_customer_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='gender_type',
        ),
    ]
