# Generated by Django 4.1 on 2022-08-10 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_ordertag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderTag',
            new_name='Order',
        ),
    ]
