# Generated by Django 4.1 on 2022-08-10 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_rename_ordertag_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[('pending', 'pending'), ('Out for delivery', 'Out for delivery'), ('delivered', 'delivered')], null=True),
        ),
    ]
